apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pacman
  labels:
    app: pacman
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
        - name: pacman
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP